### ISSUE TITLE
Not modern any more?

### ISSUE THREAD

**Issue by internalG** [KMindeguia/moviedbapp#4]
Thanks for the source for a real app. I just want to learn some from you but I find that EGOImageView is used instead of SDWebImage. So I think it's an old source right?

**Comment by KMindeguia** [comment]
Hi, thanks for reaching out!
EGOImageView is indeed quite an old source now, but I've kept it because I like how simple it is to use. To be fair, I was thinking of changing it to SDWebImage. Just haven't found the time to do it yet. So to answer your question once and for all: EGO is old, the movies app, not so much ;)

**Comment by KMindeguia** [comment]
There you go, no EGOImageView anymore :) https://github.com/KMindeguia/movies/commit/914e358fbed1f10ae115aca76122dfb3efc55b9a

**Comment by internalG** [comment]
Great quick hand👍
